# permissions for end users to view reapers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: reaper-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubescrub-operator
    app.kubernetes.io/part-of: kubescrub-operator
    app.kubernetes.io/managed-by: kustomize
  name: reaper-viewer-role
rules:
- apiGroups:
  - infra.caseywylie.io
  resources:
  - reapers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.caseywylie.io
  resources:
  - reapers/status
  verbs:
  - get
